/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/iot/solar/{projectId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get solar data for a project */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Solar metrics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/iot/satellite/{projectId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get satellite data for a project */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Satellite metrics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all projects
     * @description Paginated list using the frontend's `page`/`pageSize` contract. `limit` is an alias for `pageSize`; `cursor` is a legacy offset alias that still works.
     */
    get: {
      parameters: {
        query?: {
          /** @description 1-based page number */
          page?: number;
          /** @description Items per page (max 100) */
          pageSize?: number;
          /** @description Alias for pageSize */
          limit?: number;
          /** @description Legacy offset cursor; applied as an offset when present */
          cursor?: number;
          min_score?: number;
          max_score?: number;
          min_date?: number;
          max_date?: number;
          sort_by?:
            | "id"
            | "credit_quality"
            | "green_impact"
            | "power_output_kw"
            | "efficiency_pct"
            | "forest_density_pct"
            | "ndvi_score"
            | "timestamp";
          sort_order?: "asc" | "desc";
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paginated projects */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PaginatedProjectsResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a single project
     * @description Nested project/detail/verifiedMetadata response matching the frontend's `ProjectWithDetail` shape. Unknown or deleted ids return 404.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Project with detail */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ProjectWithDetail"];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{id}/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Score history for a project */
    get: {
      parameters: {
        query?: {
          /** @description Start timestamp (ms) */
          from?: number;
          /** @description End timestamp (ms) */
          to?: number;
          format?: "json" | "csv";
        };
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Score history entries or CSV download */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{id}/history/trend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Score trend for a project */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Trend result */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Trend"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{id}/price-history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Price and yield chart series for a project (#769)
     * @description Returns `PricePoint[]` = `{date, price, yield?}` for the project's chart. Values are derived from the on-chain `get_score_history` timestamps and the current `get_interest_rate`. `yield` is `rate_bps / 100`; `price` is `100 / (1 + yield/100)` (one-period present value). See API.md for the full formula.
     */
    get: {
      parameters: {
        query?: {
          /** @description Start timestamp (unix ms) */
          from?: number;
          /** @description End timestamp (unix ms) */
          to?: number;
          /** @description Bucket size for the series */
          interval?: "day" | "week";
        };
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description PricePoint series in ascending date order */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /**
             * @example {
             *       "project_id": 27,
             *       "interval": "day",
             *       "count": 3,
             *       "points": [
             *         {
             *           "date": "2026-09-28",
             *           "price": 96.15,
             *           "yield": 4
             *         },
             *         {
             *           "date": "2026-09-29",
             *           "price": 96.15,
             *           "yield": 4
             *         },
             *         {
             *           "date": "2026-09-30",
             *           "price": 96.15,
             *           "yield": 4
             *         }
             *       ]
             *     }
             */
            "application/json": unknown;
          };
        };
        /** @description Invalid range or interval */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unknown or archived project */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get portfolio summary */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Portfolio metrics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/score-update": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Trigger a manual score update */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Score updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/batch/score-update": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enqueue a batch score-update job */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Job accepted */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BatchJob"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/batch/{batchId}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get batch job status */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          batchId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Job status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BatchJob"];
          };
        };
        /** @description Job not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all role assignments */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Array of role entries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Assign a role to a user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Role"];
        };
      };
      responses: {
        /** @description Role assigned */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid role */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/roles/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove a role from a user */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Role removed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/webhooks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List registered webhooks */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Array of webhook configs */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Register a new webhook */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            url: string;
            secret: string;
          };
        };
      };
      responses: {
        /** @description Webhook registered */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Webhook"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/webhooks/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a webhook by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Webhook config */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    /** Remove a webhook */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Webhook removed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/creators/applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit a creator application */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            location: string;
            capacity_kw: number;
            /** @description ipfs://, https:// or ar:// URIs only. */
            documents: string[];
          };
        };
      };
      responses: {
        /** @description Application submitted */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CreatorApplication"];
          };
        };
        /** @description Invalid metadata or document URI */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Missing or invalid wallet authentication */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/creators/applications/{id}/create-project-tx": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Build an unsigned create_project transaction (#771) */
    get: {
      parameters: {
        query?: {
          sequence?: string;
          maturity_date?: number;
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Unsigned create_project XDR (never signed server-side) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Application belongs to another wallet */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Application is not approved yet */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/creators/applications/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a creator application */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Application */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CreatorApplication"];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Advance the creator application review workflow */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            status: "in_review" | "approved" | "rejected";
            actor?: string;
            note?: string;
            /** @description Whitelister G... address; when set the response includes the unsigned set_whitelist XDR. */
            whitelister?: string;
            whitelister_sequence?: string;
          };
        };
      };
      responses: {
        /** @description Updated application; includes set_whitelist_tx on approval when a whitelister is supplied */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid transition or input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error?: string;
    };
    Project: {
      id?: number;
      name?: string;
      credit_quality?: number;
      green_impact?: number;
      power_output_kw?: number;
      efficiency_pct?: number;
      forest_density_pct?: number;
      ndvi_score?: number;
      timestamp?: number;
    };
    ProjectDetail: {
      power_output_kw?: number;
      efficiency_pct?: number;
      forest_density_pct?: number;
      ndvi_score?: number;
      timestamp?: number;
      funding?: number;
    };
    ProjectWithDetail: {
      project: components["schemas"]["Project"];
      detail: components["schemas"]["ProjectDetail"];
      /** @description Whether the backend holds metadata for the project. */
      verifiedMetadata: boolean;
    };
    PaginatedProjectsResponse: {
      projects: components["schemas"]["Project"][];
      total: number;
      filtered_total?: number;
      page: number;
      pageSize: number;
      hasMore: boolean;
      /** @description Legacy cursor alias: next offset when another page follows. */
      cursor?: number;
    };
    ScoreHistory: {
      project_id?: number;
      credit_quality?: number;
      green_impact?: number;
      /** @description Unix ms timestamp */
      recorded_at?: number;
    };
    Trend: {
      /** @enum {string} */
      trend?: "improving" | "declining" | "stable";
      net_delta?: number;
      data_points?: number;
    };
    BatchJob: {
      id?: string;
      /** @enum {string} */
      status?: "pending" | "running" | "done" | "failed";
      total?: number;
      completed?: number;
      failed?: number;
      started_at?: number;
      finished_at?: number | null;
    };
    Role: {
      userId?: string;
      /** @enum {string} */
      role?: "admin" | "operator" | "viewer";
    };
    Webhook: {
      id?: string;
      url?: string;
      secret?: string;
    };
    CreatorApplication: {
      id?: string;
      wallet?: string;
      /** @enum {string} */
      status?: "submitted" | "in_review" | "approved" | "rejected";
      /** @description Validated against src/schemas/creator-application.schema.json (name, location, capacity_kw, documents). */
      metadata?: Record<string, never>;
      metadata_hash?: string | null;
      metadata_uri?: string | null;
      project_id?: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
